# Generated by Django 5.0.3 on 2024-11-23 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(default='opened', max_length=200)),
                ('auction1', models.CharField(default='0', max_length=200)),
                ('maxparticipant', models.CharField(default='0', max_length=200)),
                ('username', models.CharField(default='-', max_length=200)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionid', models.CharField(max_length=200)),
                ('itemid', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('categoryid', models.CharField(max_length=200)),
                ('subcategoryid', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('minimumbid', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('startat', models.DateTimeField(default=django.utils.timezone.now)),
                ('endat', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionid', models.CharField(max_length=200)),
                ('itemid', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('winner', models.CharField(max_length=200)),
                ('bid', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('bidtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionid', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
