# Generated by Django 5.0.3 on 2024-09-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='image', max_length=500),
        ),
    ]
