# Generated by Django 5.0.3 on 2024-09-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='itemid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
