# Generated by Django 5.0.3 on 2024-09-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='categoryid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
