# Generated by Django 5.0.3 on 2024-10-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_subcategory_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction1',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(default='open', max_length=200),
        ),
    ]
