# Generated by Django 5.0.3 on 2024-10-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_auction1_alter_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='itemid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
