# Generated by Django 5.0.3 on 2024-10-06 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_notification_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bidtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
